# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-10 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name=b'\xe6\x9c\xba\xe6\x88\xbf\xe5\x90\x8d\xe7\xa7\xb0')),
                ('location', models.CharField(blank=True, max_length=256, null=True, verbose_name=b'\xe6\x9c\xba\xe6\x88\xbf\xe4\xbd\x8d\xe7\xbd\xae')),
                ('manager', models.CharField(max_length=32, verbose_name=b'\xe7\xae\xa1\xe7\x90\x86\xe4\xba\xba')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name=b'\xe6\x89\x8b\xe6\x9c\xba')),
            ],
            options={
                'verbose_name': '\u673a\u623f\u4fe1\u606f',
                'verbose_name_plural': '\u673a\u623f\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=64, verbose_name=b'\xe4\xb8\xbb\xe6\x9c\xba\xe5\x90\x8d\xe7\xa7\xb0')),
                ('sys_version', models.CharField(choices=[(b'1', b'Centos 6.8'), (b'2', b'Centos 7.2'), (b'3', b'Window Server 2003'), (b'4', b'Window Server 2008'), (b'5', b'Other System')], default=b'1', max_length=32, verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c\xe7\xb3\xbb\xe7\xbb\x9f')),
                ('comments', models.CharField(blank=True, max_length=256, null=True, verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'verbose_name': '\u4e3b\u673a\u4fe1\u606f',
                'verbose_name_plural': '\u4e3b\u673a\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_v4', models.GenericIPAddressField(verbose_name=b'V4\xe5\x9c\xb0\xe5\x9d\x80')),
                ('ssh_port', models.IntegerField(default=22, verbose_name=b'\xe8\xbf\x9c\xe7\xa8\x8b\xe7\xab\xaf\xe5\x8f\xa3')),
                ('ssh_user', models.CharField(max_length=32, verbose_name=b'SSH\xe7\x94\xa8\xe6\x88\xb7')),
                ('ssh_pass', models.CharField(blank=True, max_length=128, null=True, verbose_name=b'SSH\xe5\xaf\x86\xe7\xa0\x81')),
                ('ssh_pri_key', models.CharField(default=b'/root/.ssh/id_rsa', max_length=128, verbose_name=b'SSH\xe7\xa7\x98\xe9\x92\xa5')),
                ('is_pass', models.CharField(choices=[(b'1', b'\xe6\x98\xaf'), (b'0', b'\xe5\x90\xa6')], default=b'1', max_length=2, verbose_name=b'\xe5\xaf\x86\xe7\xa0\x81\xe8\xbf\x9e\xe6\x8e\xa5')),
                ('is_used', models.BooleanField(default=True, verbose_name=b'\xe5\x90\xaf\xe7\x94\xa8')),
                ('comments', models.CharField(blank=True, max_length=256, null=True, verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'verbose_name': '\u7ba1\u7406\u5730\u5740',
                'verbose_name_plural': '\u7ba1\u7406\u5730\u5740',
            },
        ),
        migrations.AddField(
            model_name='host',
            name='host_ip',
            field=models.ManyToManyField(to='Assets.Ip', verbose_name=b'\xe7\xbb\x91\xe5\xae\x9a\xe5\x9c\xb0\xe5\x9d\x80'),
        ),
        migrations.AddField(
            model_name='host',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assets.DataCenter', verbose_name=b'\xe6\x9c\xba\xe6\x88\xbf'),
        ),
    ]
